name: kaduna
channels:
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.0.6
  - streamlit=1.26.0
  - pandas=2.0.3
  - geopandas=0.14.0
  - scikit-learn=1.3.1
  - plotly=5.17.0
  - folium=0.14.0
  - seaborn=0.12.2
  - openpyxl=3.0.10
  - pip:
    - st-dbscan==0.2.2